name: Flutter_Analyzer_Formatter

on:
  pull_request:
    branches: [main]

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.1"
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format ./ --set-exit-if-changed